using FluentAssertions;
using MarkdownToPdf.Web.Features.PdfGeneration;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.DependencyInjection;
using System.Net;
using System.Text.RegularExpressions;
using Xunit;

namespace MarkdownToPdf.Tests.Features.PdfGeneration;

public sealed class GeneratePdfIntegrationTests : IClassFixture<WebApplicationFactory<Program>>
{
    private readonly HttpClient _client;

    public GeneratePdfIntegrationTests(WebApplicationFactory<Program> factory)
    {
        // 2. Intercept the WebApplicationFactory to swap out the real service with the Fake
        var clientOptions = new WebApplicationFactoryClientOptions { AllowAutoRedirect = false };

        _client = factory.WithWebHostBuilder(builder =>
        {
            builder.ConfigureServices(services =>
            {
                // Find the existing Puppeteer registration and remove it
                var descriptor = services.SingleOrDefault(d => d.ServiceType == typeof(IPdfService));
                if (descriptor != null)
                {
                    services.Remove(descriptor);
                }

                // Inject our lightning-fast fake
                services.AddSingleton<IPdfService, FakePdfService>();
            });
        }).CreateClient(clientOptions);
    }

    [Fact]
    public async Task Post_GeneratePdf_ShouldReturnHtmlToast_WhenValidationFails()
    {
        // 1. Arrange: GET the page to establish a session and grab the Antiforgery token
        var getResponse = await _client.GetAsync("/");
        var html = await getResponse.Content.ReadAsStringAsync();

        var tokenMatch = Regex.Match(html, @"name=""__RequestVerificationToken"" type=""hidden"" value=""([^""]+)""");
        var token = tokenMatch.Success ? tokenMatch.Groups[1].Value : "";

        // Grab the Antiforgery cookie and attach it to the client
        var cookies = getResponse.Headers.GetValues("Set-Cookie");
        _client.DefaultRequestHeaders.Add("Cookie", cookies);

        // 2. Prepare payload including the extracted token
        var content = new FormUrlEncodedContent([
            new KeyValuePair<string, string>("MarkdownText", ""),
            new KeyValuePair<string, string>("__RequestVerificationToken", token)
        ]);

        // 3. Act: Hit the endpoint
        var response = await _client.PostAsync("/api/pdf/generate", content);
        var responseString = await response.Content.ReadAsStringAsync();

        // 4. Assert: We now receive our custom HTML Toast instead of a generic text error
        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
        response.Content.Headers.ContentType?.MediaType.Should().Be("text/html");
        responseString.Should().Contain("Oops! Please type or paste some Markdown");
    }

    [Fact]
    public async Task Post_GeneratePdf_ShouldReturnRedirectAndServePdf_WhenMarkdownIsValid()
    {
        // 1. Arrange: GET the page to establish a session and grab the Antiforgery token
        var getResponse = await _client.GetAsync("/");
        var html = await getResponse.Content.ReadAsStringAsync();

        var tokenMatch = Regex.Match(html, @"name=""__RequestVerificationToken"" type=""hidden"" value=""([^""]+)""");
        var token = tokenMatch.Success ? tokenMatch.Groups[1].Value : "";

        var cookies = getResponse.Headers.GetValues("Set-Cookie");
        _client.DefaultRequestHeaders.Add("Cookie", cookies);

        // Provide a valid markdown payload this time
        var content = new FormUrlEncodedContent([
            new KeyValuePair<string, string>("MarkdownText", "# Valid Markdown Test"),
            new KeyValuePair<string, string>("__RequestVerificationToken", token)
        ]);

        // 2. Act: Hit the Generate endpoint
        var generateResponse = await _client.PostAsync("/api/pdf/generate", content);

        // 3. Assert (Generation): We expect a 200 OK and an HX-Redirect header
        generateResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        generateResponse.Headers.Contains("HX-Redirect").Should().BeTrue();

        // Extract the redirect URL dynamically generated by the server
        var redirectUrl = generateResponse.Headers.GetValues("HX-Redirect").First();
        redirectUrl.Should().Contain("/api/pdf/download/");

        // ==========================================================
        // 4. Act: Follow the redirect to test the Download Endpoint
        // ==========================================================
        var downloadResponse = await _client.GetAsync(redirectUrl);

        // Assert (Download): Ensure the file is served correctly as a PDF
        downloadResponse.StatusCode.Should().Be(HttpStatusCode.OK);
        downloadResponse.Content.Headers.ContentType?.MediaType.Should().Be("application/pdf");

        // ==========================================================
        // 5. Act & Assert: The "Sad Path" Download (Expired/Fake ID)
        // ==========================================================
        var fakeIdUrl = $"/api/pdf/download/{Guid.NewGuid()}";
        var invalidDownloadResponse = await _client.GetAsync(fakeIdUrl);

        // If a user guesses a GUID or their 5-minute cache expires, it must return 404 cleanly
        invalidDownloadResponse.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }
}